### ISSUE TITLE
Contact Us link - takes user to new page vs new window

### ISSUE THREAD

**Issue by PeterPhillips55** [Challenged-Sailors-San-Diego/main-site#10]
Sunroad Marina
 Contact Us link - takes user to new page vs opening new window.  Same is true on Getting Here page.

![Sunroad link](https://github.com/Challenged-Sailors-San-Diego/main-site/assets/143907127/8a3483f3-4b7d-49cd-9c2f-8eedb09c615c)

**Comment by rysllvn** [comment]
fixed all links on both of these pages (contact, getting here)

**Comment by PeterPhillips55** [comment]
pass
