### ISSUE TITLE
Contact page - Getting Here link

### ISSUE THREAD

**Issue by PeterPhillips55** [Challenged-Sailors-San-Diego/main-site#11]
Contact page - Getting Here page link goes to new page versus opening a new page - BUG
![Contact - Getting Here link](https://github.com/Challenged-Sailors-San-Diego/main-site/assets/143907127/5188f99d-b102-4d5a-870d-9de24f68db2c)

**Comment by rysllvn** [comment]
I think either way is valid for a link to another page on the site like this. It is now changed though to open a new tab when clicking.

**Comment by PeterPhillips55** [comment]
Pass
