### ISSUE TITLE
no menu item in footer for Adaptive Sailor

### ISSUE THREAD

**Issue by PeterPhillips55** [Challenged-Sailors-San-Diego/main-site#14]
no menu item in footer for Adaptive Sailor.    - Content
Consider that the menu should be prioritized, the top 3 are always the top 3:
Adaptive Sailing - Go Sailing!
Volunteer
Give
Calendar
Yada
Yada

**Comment by rysllvn** [comment]
Added this. The order matches the top nav bar where Calendar comes before volunteer and give.

**Comment by PeterPhillips55** [comment]
Please change both so that they are in the order:  
Adaptive Sailing - Go Sailing!
Volunteer
Give
Calendar

**Comment by rysllvn** [comment]
@PeterPhillips55 changed

**Comment by PeterPhillips55** [comment]
Passed - thank you.
