### ISSUE TITLE
Volunteer "Go Sailing" Form doesn't send to info@challengedSailors.org

### ISSUE THREAD

**Issue by PeterPhillips55** [Challenged-Sailors-San-Diego/main-site#5]
Volunteer "Go Sailing" Form doesn't send to info@challengedSailors.org.  Notification indicates that "Application Submitted.  We'll be in touch with you soon" - BUG - Priority 1 - Showstopper

**Comment by rysllvn** [comment]
Please test again when you have time. Should be working now.

**Comment by PeterPhillips55** [comment]
Nope.  Not working.  Fail

**Comment by rysllvn** [comment]
I doesn't have access, but according to Sam these are going to the spam folder. Depending on who is providing the email address there should be a few ways to do this.

**Comment by PeterPhillips55** [comment]
Understood.  pass
