### ISSUE TITLE
Go Sailing form - Allows to submit without "Most Interersted in" role being selected

### ISSUE THREAD

**Issue by PeterPhillips55** [Challenged-Sailors-San-Diego/main-site#6]
Go Sailing form - Allows to submit without "Most Interested in" role being selected.  This needs to be a required field - BUG

**Comment by rysllvn** [comment]
fixed

**Comment by PeterPhillips55** [comment]
Pass.  I really like this design, where Adaptive Sailing is the default and the volunteer options only appear if Volunteering is selected.  Great fix!
